#Assignment 2
#Muhammad Sakhran Thayyib - 2206046790

import string
import htmlFunctions 

print("Program to create word cloud from a text file")
print("------------------------------------------------")
print(" The result is stored as an HTML file\n", "which can be displayed in a web browser.")

tempFile = """Remarks by Indonesian President Joko "Jokowi" Widodo at the APEC CEO Summit on November 10, 2014, in Beijing, China. 

Excellencies, distinguished guests, ladies and gentlemen, and CEOs, good morning.

First, on behalf of the Indonesian Government and the people of Indonesia, I would like to thank you for coming to my presentation. Today, I am happy, I am very happy, to be with you, because you know I was a businessman years ago. So, this morning, I am very happy because we can talk about business, about investment with all of you.

The picture shows you our map of Indonesia. We have a population of 240 million and the distance is like from London in UK to Istanbul in Turkey. And imagine, we have 17,000 islands. 17,000 islands.

Our national budget for 2015 is $167 billion and for fuel subsidy is $27 billion. It's huge. So we want to channel our fuel subsidy from consumption to the productive activities. From consumptive activities to productive activities. We want to channel our fuel subsidy to the farm for seeds, for fertilizers, and also for irrigation. And we want to build dams � 25 dams in 5 years from our fuel subsidy to maintain the water supply to the farming area.

Some subsidy we want to channel to the fishermen, to give them boat engines, to give them refrigerators. We want to increase the income of the fishermen. Some fuel subsidy we want to give to micro and small enterprises in the villages. We want to help them raise their working capital. And some subsidy we want to channel to the health program, the education program. And some subsidy we want to channel to infrastructure.

In 5 years we want to build 24 seaports and deep seaports. As you know, we have 17,000 islands, so we need seaports and we need deep seaports. And this is your opportunity: 24 seaports and deep seaports.

The picture shows our Jakarta Port, Tanjung Priok port. In 2009, the capacity is 3.6 million TEUs a year, and our plan in 2017 is around 15 million TEUs a year. This is the potential ports in Indonesia. This is your opportunity. We want to build in Sumatera island, in Kalimantan island, in Java island, in Sulawesi island, in Maluku island, also in Papua island.

And we plan to build our railway track, railway network. Now we have already in Java and we want to build in Sumatera island, in Kalimantan island, in Sulawesi island and also in Papua island. This is your opportunity.

Now we talk about mass transportation. We want to build our mass transportation in 6 big cities in Indonesia. We have started in Jakarta last year, and we want to build in Medan, in Makassar, in Semarang, in Bandung, in Surabaya. So, this is also your opportunity, because you know our national budget is limited.

Now we talk about our maritime agenda. We want to build sea toll. What is sea toll? Sea toll is maritime transportation system to make our transportation cost lower, to make our transportation cost more efficient. We want to build from the west to the east. We hope not only the vessels can enter our sea toll but also mother vessels can enter the sea toll. So, the price, the cost of the transportation is more efficient.

For example, the price of the cement, one sack cement, in Java island is $6 per sack cement. But in Papua island the price is $150 per sack cement. Imagine, 25 times. So we hope with our sea toll the price in our islands is the same.

Electricity. We need power plants. We need around 35,000 megavolts to build our industries, to build our projects, to build our industrial zones, our manufacturing zones. So, we need power plants. This is also your opportunity to invest in this project. Because we need our power plants for manufacturing, for industrial zones.

Many investors, a lot of investors, when they come to me, most of them they always complain about land acquisition. I will push my ministers, my governors, my mayors, to help clear this problem. I have experience with land acquisition when I was a governor. We have a project, the Jakarta Outer Ring Road, started 15 years ago but was stopped 8 years ago, because we have a problem here: 1.5 kilometers unfinished because there is 143 families who do not accept with the compensation price. So last year I invite them. I go to them then I invite them to lunch and dinner. Four times. Ah, this is me. I invite them and then we talk about the problem. Four times. Four times meeting. And the problem is cleared.

And now the toll road has been used (starting) 7 month ago.

Now we talk business permit. We have national one-stop service office that can help you, that will serve you, that will facilitate you, that will give you your business permit. For example, principle business permit needs 3 days to process.

Finally, again on behalf of the Indonesian government and the people of Indonesia, I would like to thank you for your listening (to) my presentation. We are waiting for you to come to Indonesia. We are waiting for you to invest in Indonesia.

Thank you.

Good morning.

Notes: island island island. """

tempStopWords = """
-
--
2014
2015
a's
a
able
about
above
according
accordingly
across
actually
after
afterwards
again
against
ain't
aint
all
allow
allows
almost
alone
along
already
also
although
always
am
among
amongst
an
and
another
any
anybody
anyhow
anyone
anything
anyway
anyways
anywhere
apart
appear
appreciate
appropriate
are
aren't
arent
around
as
aside
ask
asking
associated
at
available
away
awfully
be
became
because
become
becomes
becoming
been
before
beforehand
behind
being
believe
below
beside
besides
best
better
between
beyond
both
brief
but
by
c'mon
cmon
c's
c
came
can
can't
cant
cannot
cant
cause
causes
certain
certainly
changes
clearly
co
com
come
comes
concerning
consequently
consider
considering
contain
containing
contains
corresponding
could
couldn't
couldnt
course
currently
definitely
described
despite
did
didn't
didnt
different
do
does
doesn't
doesnt
doing
don't
dont
done
down
downwards
during
each
edu
eg
eight
either
else
elsewhere
enough
entirely
especially
et
etc
even
ever
every
everybody
everyone
everything
everywhere
ex
exactly
example
except
far
few
fifth
first
five
followed
following
follows
for
former
formerly
forth
four
from
further
furthermore
get
gets
getting
given
gives
go
goes
going
gone
got
gotten
greetings
had
hadn't
hadnt
happens
hardly
has
hasn't
hasnt
have
haven't
havent
having
he
he's
hes
hello
help
hence
her
here
here's
heres
hereafter
hereby
herein
hereupon
hers
herself
hi
him
himself
his
hither
hopefully
how
howbeit
however
i
i'd
id
i'll
ill
i'm
im
i've
ive				
ie
if
ignored
immediate
in
inasmuch
inc
indeed
indicate
indicated
indicates
inner
insofar
instead
into
inward
is
isn't
isnt
it
it'd
itd
it'll
itll
it's
its
itself
just
keep
keeps
kept
know
knows
known
last
lately
later
latter
latterly
least
less
lest
let
let's
lets
like
liked
likely
little
look
looking
looks
ltd
mainly
many
may
maybe
me
mean
meanwhile
merely
might
more
moreover
most
mostly
much
must
my
myself
name
namely
nd
near
nearly
necessary
need
needs
neither
never
nevertheless
new
next
nine
no
nobody
non
none
noone
nor
normally
not
nothing
novel
now
nowhere
obviously
of
off
often
oh
ok
okay
old
on
once
one
ones
only
onto
or
other
others
otherwise
ought
our
ours
ourselves
out
outside
over
overall
own
particular
particularly
per
perhaps
placed
please
plus
possible
presumably
probably
provides
que
quite
qv
rather
rd
re
really
reasonably
regarding
regardless
regards
relatively
respectively
right
said
same
saw
say
saying
says
second
secondly
see
seeing
seem
seemed
seeming
seems
seen
self
selves
sensible
sent
serious
seriously
seven
several
shall
she
should
shouldn't
shouldnt
since
six
so
some
somebody
somehow
someone
something
sometime
sometimes
somewhat
somewhere
soon
sorry
specified
specify
specifying
still
sub
such
sup
sure
t's
ts
take
taken
tell
tends
th
than
thank
thanks
thanx
that
that's
thats
the
their
theirs
them
themselves
then
thence
there
there's
theres
thereafter
thereby
therefore
therein
theres
thereupon
these
they
they'd
theyd
they'll
theyll
they're
theyre
they've
theyve
think
third
this
thorough
thoroughly
those
though
three
through
throughout
thru
thus
to
together
too
took
toward
towards
tried
tries
truly
try
trying
twice
two
un
under
unfortunately
unless
unlikely
until
unto
up
upon
us
use
used
useful
uses
using
usually
value
various
very
via
viz
vs
want
wants
was
wasn't
wasnt
way
we
we'd
wed
we'll
well
we're
were
we've
weve
welcome
well
went
were
weren't
werent
what
what's
whats
whatever
when
whence
whenever
where
where's
wheres
whereafter
whereas
whereby
wherein
whereupon
wherever
whether
which
while
whither
who
who's
whos
whoever
whole
whom
whose
why
will
willing
wish
with
within
without
won't
wont
wonder
would
would
wouldn't
wouldnt
yes
yet
you
you'd
youd
you'll
youll
you're
youre
you've
youve
your
yours
yourself
yourselves
zero
"""

fileNoPunc = tempFile.translate(str.maketrans('','', string.punctuation))
fileTest = fileNoPunc.lower().split().sort()
fileBetterNow = []


print()
print("JokoWidodoSpeech.txt: ", fileTest )
print()
print("60 words in frequency order as (count:word) pairs")
print()

